- name: Setup Host
  hosts: pi
  vars:
    - homelab_dir: /home/vorant94/homelab
  tasks:
    - name: APT Update
      ansible.builtin.import_tasks:
        file: ../tasks/apt-update.yml

    - name: Install Docker
      ansible.builtin.import_tasks:
        file: ../tasks/install-docker.yml

    - name: Push source
      ansible.builtin.import_tasks:
        file: ../tasks/push-source.yml
