- name: Setup Containers
  hosts: pi
  vars:
    homelab_dir: /home/vorant94/homelab
  tasks:
    - name: Compose Up
      ansible.builtin.import_tasks:
        file: ../tasks/compose-up.yml

    - name: Setup Vaultwarden
      ansible.builtin.import_tasks:
        file: ../tasks/setup-vaultwarden.yml
