- name: First-time Setup
  hosts: pi
  vars:
    - homelab_dir: /home/vorant94/homelab
  tasks:
    - name: Update all
      ansible.builtin.import_tasks:
        file: ../tasks/update-all.yml

    - name: Install Docker
      ansible.builtin.import_tasks:
        file: ../tasks/install-docker.yml

    - name: Sync source
      ansible.builtin.import_tasks:
        file: ../tasks/sync-source.yml



