- name: Update
  hosts: pi
  vars:
    homelab_dir: /home/vorant94/homelab
  tasks:
    - name: APT Update
      ansible.builtin.import_tasks:
        file: ../tasks/apt-update.yml

    - name: Push source
      ansible.builtin.import_tasks:
        file: ../tasks/push-source.yml

    - name: Compose Restart
      ansible.builtin.import_tasks:
        file: ../tasks/compose-restart.yml
