# Push source
---
- name: Pull repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/vorant94/homelab.git
    force: true
    dest: "{{ homelab_dir }}"

- name: Push Nginx pi.lan KEY
  become: true
  ansible.builtin.copy:
    src: ../ssl/pi.lan.key
    dest: "{{ homelab_dir }}/docker/nginx/private/pi.lan.key"

- name: Push Nginx pi.lan CRT
  become: true
  ansible.builtin.copy:
    src: ../ssl/pi.lan.crt
    dest: "{{ homelab_dir }}/docker/nginx/certs/pi.lan.crt"

- name: Push Heimdall env
  become: true
  ansible.builtin.copy:
    src: ../../docker/heimdall/.env
    dest: "{{ homelab_dir }}/docker/heimdall/.env"

- name: Push Pihole env
  become: true
  ansible.builtin.copy:
    src: ../../docker/pihole/.env
    dest: "{{ homelab_dir }}/docker/pihole/.env"

- name: Push Pihole DNS records
  become: true
  ansible.builtin.copy:
    content: |
      {{ lookup('env','PI_IP') }}   pi.lan
      {{ lookup('env','PI_IP') }}   vaultwarden.pi.lan
      {{ lookup('env','PI_IP') }}   jellyfin.pi.lan
    dest: "{{ homelab_dir }}/docker/pihole/pihole/custom.list"

- name: Push Vaultwarden env
  become: true
  ansible.builtin.copy:
    src: ../../docker/vaultwarden/.env
    dest: "{{ homelab_dir }}/docker/vaultwarden/.env"

- name: Push Jellyfin env
  become: true
  ansible.builtin.copy:
    src: ../../docker/jellyfin/.env
    dest: "{{ homelab_dir }}/docker/jellyfin/.env"

- name: Push Postgres env
  become: true
  ansible.builtin.copy:
    src: ../../docker/postgres/.env
    dest: "{{ homelab_dir }}/docker/postgres/.env"
