# Push source
---
- name: Pull repo
  # TODO try to avoid become: true here
  become: true
  ansible.builtin.git:
    repo: https://github.com/vorant94/homelab.git
    force: true
    dest: "{{ homelab_dir }}"

- name: Push docker ignored files (env, certs etc.)
  # TODO try to avoid become: true here
  become: true
  ansible.posix.synchronize:
    src: ../../docker/
    dest: "{{ homelab_dir }}/docker/"

